// 카테고리 데이터를 배열로 정의
export const Category = [
  { name: 'BEST 100', link: '/best-100' },
  { name: 'NEW 10%', link: '/new-10' },
  { name: 'SEASON ~90%', link: '/season' },
  { name: 'SET', link: '/set' },
  { name: 'OUTER', link: '/outer' },
  { name: 'DRESS', link: '/dress' },
  { name: 'TOP', link: '/top' },
  { name: 'BOTTOM', link: '/bottom' },
  { name: 'JACKET', link: '/jacket' },
  { name: 'COAT', link: '/coat' },
  { name: 'VEST', link: '/vest' },
  { name: 'PADDED', link: '/padded ' },
  { name: 'CARDIGAN', link: '/cardigan' },
  { name: 'KNIT', link: '/knit' },
  { name: 'T-SHIRT', link: '/t-shirt' },
  { name: 'BLOUSE', link: '/blouse' },
  { name: 'SHIRT', link: '/shirt' },
  { name: 'SLEEVELESS', link: '/sleeveless' },
  { name: 'SWEATSHIRT', link: '/sweatshirt' },
  { name: 'HOODIE', link: '/hoodie' },
  { name: 'SKIRT', link: '/skirt' },
  { name: 'CASUAL_PANTS', link: '/casual_pants' },
  { name: 'DENIM', link: '/denim' },
  { name: 'SHORTS', link: '/shorts' },
  { name: 'LEGGINGS', link: '/leggings' },
  { name: 'FLARE', link: '/flare' },
  { name: 'A-LINE', link: '/a-line' },
  { name: 'H-LINE', link: '/h-line' },
  { name: 'PATTERN', link: '/pattern' },
  { name: 'PLAIN', link: '/plain' },
  { name: 'CHIFFON', link: '/chiffon' },
  { name: 'LACE', link: '/lace' },
  { name: 'GUEST_LOOK', link: '/guest_look' },
  { name: 'DRESS', link: '/dress' },
  { name: 'SLACKS', link: '/slacks' },
  { name: '', link: '/' },
];